% x = theta 1
% y = theta 2
%% Equations of motion
tau = x_dd.*(0.5*m*(l^2)*cos(x-y) +0.5*M*(l^2) + I) ...
    + y_dd.*(0.25*m*(l^2) + M*(l^2) + I) ...
    - (x_d.^2).*(0.5*(l^2)*sin(x-y)*(m + M)) ...
    + k*(y-x) - (3/2)*m*g*l*sin(y);

tau = x_dd.*((3/4)*m*(l^2) + M*(l^2) + 2*I) ...
    + y_dd.*(0.5*m*(l^2)*cos(x-y) + 0.5*M*(l^2)*cos(x-y) + I) ...
    + (x_d.^2)*(0.5*m*(l^2)*sin(x-y) + 0.5*M*(l^2)*sin(x-y)) ...
    - (5/2)*m*g*l*sin(x) - k*(y-x);
%%
 x_dd = -(y_dd.*(0.5*m*(l^2)*cos(x-y) + 0.5*M*(l^2)*cos(x-y) + I) ...
      + (x_d.^2)*(0.5*m*(l^2)*sin(x-y) + 0.5*M*(l^2)*sin(x-y)) ...
      - (5/2)*m*g*l*sin(x) - k*(y-x) - tau)./((3/4)*m*(l^2) + M*(l^2) + 2*I);



